const express = require('express');
const route  = express.Router();  
const setting = require('../events/setting') 
module.exports = app=>{   
    route.get('/setting/general',setting.index)
    route.get('/edit_description',setting.edit_description)
    route.post('/update_description',setting.update_decription)
    route.get('/edit_name',setting.edit_name)
    route.post('/update_name',setting.update_name)
    route.get('/edit_email',setting.edit_mail)
    route.get('/edit_user',setting.edit_user) 
    route.get('/edit_work',setting.edit_work)
    route.post('/update_work',setting.update_work)
    route.get('/edit_ocupation',setting.edit_ocupation)
    route.post('/update_ocupation',setting.update_ocupation)
    route.get('/edit_language',setting.edit_language)  
    route.post('/update_language',setting.update_language)  
    route.get('/edit_address',setting.edit_address) 
    route.post('/update_addres',setting.update_address)
    route.get('/edit_phone',setting.edit_phone) 
    route.post('/update_phone',setting.update_phone) 
    route.get('/edit_direction',setting.edit_direction) 
    route.post('/update_direction',setting.update_direction) 
    route.get('/edit_birtday',setting.edit_birtday)
    route.post('/update_birtday',setting.update_birtday)
    route.post('/setting/birtday/:status',setting.birtday_show)
    route.post('/setting/data_register/:status',setting.data_register_show)
    route.post('/setting/comment/:status',setting.comment_show)
    route.get('/setting/language_ubication',setting.lang_ub)
    route.get('/setting/privacity',setting.privacity)    
    route.get('/privacity/checked',setting.privacity_checked)
    route.get('/setting/log_in',setting.log_in)
    route.get('/setting/change_password',setting.change_pass) 
    route.post('/change_profile',setting.change_profile)
    app.use(route)
};